name: Claude Assistant

on:
  issue_comment:
    types: [created, edited]

jobs:
  post_claude_response:
    if: contains(github.event.comment.body, '@!claude')
    runs-on: ubuntu-latest

    steps:
    - name: Get stripped and trimmed comment body
      id: get-comment-body
      run: echo content=$(echo "$comment_body" | sed 's/@!claude//g' | tr -d '[:space:]') >> $GITHUB_OUTPUT

    - name: Get Claude's response to issue comment
      id: claude-response
      if: ${{ steps.get-comment-body.outputs.content != '' }}
      run: |
        echo response=$(curl https://api.anthropic.com/v1/messages \
            --header "x-api-key: ${{ secrets.ANTHROPIC_API_KEY }}" \
            --header "anthropic-version: 2023-06-01" \
            --header "content-type: application/json" \
            --data \
            '{
                "model": "claude-3-haiku-20240307",
                "max_tokens": 1024,
                "messages": [
                    {"role": "user", "content": ${{ steps.get-comment-body.outputs.content }}}
                ]
            }') >> $GITHUB_OUTPUT

    - name: Create comment
      uses: peter-evans/create-or-update-comment@v4
      with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            "@claude_response

            > ${{ steps.get-comment-body.outputs.content }}

            ${{ steps.claude-response.outputs.response }}"
